[package]
name = "great_kingdom_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "great_kingdom_core"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.25" }

[dev-dependencies]
pretty_assertions = "1.4"
